# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e89b301253b745a031a7c752a11d3f3a8dfd72d1d862e952f76108fda1761abb497494778a548864d92e26739adc65f246c812d7a3f88dbce10e73397db17be4

test:
  secret_key_base: 04e3ce298741955328bd819f4748c9d7787529e1a3f3649828df4b5958b2b8de01a99c041e89419580eac1a30287fa69d4410e21233b00adbd48e3cb5c109df1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
